### ISSUE TITLE
Кик юзера

### ISSUE THREAD

**Issue by ghost** [fakemancat/vkbot-core#2]
Хочу сделать чтобы при использовании бана, юзера, кого я баню кикало, но не понимаю как это сделать. Пробовал по разному, и через vk.api.messgaes.removeChatUser и через api call все равно не робит

**Comment by fakemancat** [comment]
Смотри, вот у тебя код
```js
user.ban.isBanned = true;
user.ban.reason = reason;
db.write();

msg.ok(`Пользователь [id${user.id}|${user.nick}] успешно забанен по причине: "${reason}"`);
```

Вот теперь вместо ```msg.ok(`Пользователь [id${user.id}|${user.nick}] успешно забанен по причине: "${reason}"`);``` вставь такую конструкцию:

```js
msg.vk.api.messages.removeChatUser({
    chat_id: msg.chatId,
    member_id: ID
}).then(() => {
    msg.ok(`Пользователь [id${user.id}|${user.nick}] успешно забанен и кикнут по причине: "${reason}"`);
}).catch((error) => {
    msg.error(`Ошибка при исключении пользователя: ${error.message}`);
});
```

Возможно у тебя была проблема в том, что ты не передал параметр vk в функции:
```js
func: async(msg, { db }) => { ... }
```
Вот там, где у тебя ```{ db }``` нужно добавить ещё vk: ```{ db, vk }```. Но доступ к ```vk``` можно получить так, как я показал выше, через ```msg```: ```msg.vk.api...```
