### ISSUE TITLE
Кик юзера по screen_name.

### ISSUE THREAD

**Issue by ghost** [fakemancat/vkbot-core#4]

**Comment by ghost** [comment]
Не очень понимаю как сделать кик юзера по screen_name

делал так: 
let scrnname = msg.fwds[0] ? msg.fwds[0].senderId : msg.text.split(' ')[1]; 
msg.vk.api.users.get({
			user_ids: scrnname,
			fields: 'id'
});

		msg.vk.api.messages.removeChatUser({
			chat_id: msg.chatId,
			member_id: ID
}).then(() => {
    msg.ok(`Пользователь [scrname|${user.nick}] успешно забанен и кикнут по причине: "${reason}"`);
}).catch((error) => {
    msg.error(`Ошибка при исключении пользователя: ${error.message}`);
});
 не получается

**Comment by IIbroII** [comment]
Ну смотри...такого fields там в принципе нет, я думаю что там надо как-то через метод utils.resolveScreenName

**Comment by noahmontelli** [comment]
реализовано через users.get
