### ISSUE TITLE
Использование команд с ID через упоминание

### ISSUE THREAD

**Issue by IIbroII** [fakemancat/vkbot-core#6]
Помогите пожалуйста, не могу никак сделать чтобы бот мог использовать команды через упоминание(например @id1), а не вводя цифровой ID или ссылку

**Comment by fakemancat** [comment]
в файле конфигурации добавить в массив ```bot_name_string``` значение такого типа: [clubID|@ID]
Например: ```let bot_name_string = ['кот', '[club168657698|@168657698]'];```
